### ISSUE TITLE
Crash On ROM Generation

### ISSUE THREAD

**Issue by AllenSeitz** [gameboy9/DW3Randomizer#11]
Using the newly uploaded 1.0 version, on Windows 10.

1) My ROM checksum matches the required one.
2) Pick my options, click generate.
3) The guide.txt file is created, but it only has equipment.
4) App is hung.

I downloaded the version right before 1.0 and this did not happen.

**Comment by AllenSeitz** [comment]
Update: running a previous version of the randomizer, then running the 1.0 version, allows the 1.0 version to work. Maybe test the 1.0 version in a clean environment?

**Comment by AllenSeitz** [comment]
Oh, no, running the previous version only helped because it altered lastFile.txt, which cleared a bunch of flags.

The flag that is hanging the randomizer is "Randomize Treasures"

**Comment by gameboy9** [comment]
This was also reported by JanusZeal this morning.  I will look at it ASAP.

**Comment by gameboy9** [comment]
Bug is fixed and released in version 1.0.1.
