### ISSUE TITLE
Echo Flute Hangs Game

### ISSUE THREAD

**Issue by AllenSeitz** [gameboy9/DW3Randomizer#12]
1) Seed 617988268 flags 0ay@z (all flags)
2) Buy Echo Flute in Knave.
3) Use Echo Flute in Aliahan town. Hear echo?
4) Use Echo Flute in Reeve. Music never changes, game hangs.

**Comment by AllenSeitz** [comment]
Additionally:
- The only chest in Aliahan town is the unreachable one in the vault. Just to check, I cheated to reach it, and it was empty. (good)
- I did take the 6 chests in Aliahan Castle: four Zombie Slashers, an Agility Seed, and a Mimic!
- I did NOT search the ground for the Magic Ball before progressing to Romaly, now it seems I cannot? If this was an orb then I am also softlocked.

**Comment by AllenSeitz** [comment]
Update: seems like the Echo Flute hangs on any non-overworld screen in which it would not echo.
- Pyramid has two orbs in the first room (lol): echo works as intended.
- Take all Pyramid chests, use Echo Flute: softlock.

**Comment by gameboy9** [comment]
This is now resolved and released in version 1.0.2.
