### ISSUE TITLE
Unable to Obtain Rainbow Drop

### ISSUE THREAD

**Issue by AllenSeitz** [gameboy9/DW3Randomizer#14]
This is in the newly patched 1.0 version with randomize treasures turned on.

I obtained the Sacred Amulet directly from Rubiss at the top of Rubiss' Tower. Apparently that one item wasn't randomized. (Lucky?) However, the Rainbow Drop guy refused to acknowledge it even when I equipped it to my hero. (The Stones of Sunlight and Staff of Rain were also in my hero's inventory.)

I cheated to get over the rainbow bridge and the game was winnable otherwise.

**Comment by AllenSeitz** [comment]
I failed to read. This is a duplicate of #6.

**Comment by gameboy9** [comment]
... but nevertheless appreciated.  May I have a seed and flags please?
