### ISSUE TITLE
Spells Not Appearing In This Seed

### ISSUE THREAD

**Issue by AllenSeitz** [gameboy9/DW3Randomizer#16]
My spell lists for my Hero, Pilgrim, and Wizard are all each 2 spells away from complete. However, none of them know Repel, Bikill, BeDragon, or RobMagic. But all 3 of them know Revive!

Those 4 missing spells are kind of important, especially Repel and RobMagic. I played another seed and got RobMagic early, so I guess it's just luck of the draw. But maybe consider ensuring that every spell in the game appears at least once, somewhere, on one of the spell lists?

**Comment by AllenSeitz** [comment]
Correction: my hero was maxed, my pilgrim was missing one spell, and my wizard was missing 3. And I'm also missing Ironize. (Although I sure didn't "miss" Ironize heh.)

**Comment by gameboy9** [comment]
I'm placing this up for opinion (this would affect DW4R as well)... if it's mostly in favor, I will look into it.

**Comment by gameboy9** [comment]
As this was indeed mostly in favor, I will implement.  So what I will do is take all of the spells, shuffle them, then distribute to the characters one by one to avoid the fun issue where a character could learn a spell twice.

**Comment by gameboy9** [comment]
This is resolved and released, so I will close.  Please reopen if there is still an issue.  Thanks!
