### ISSUE TITLE
False Negative for Echo Flute in Kidnapper's Cave

### ISSUE THREAD

**Issue by AllenSeitz** [gameboy9/DW3Randomizer#18]
Seed/Flags: 437787063 / 0qy@z

This seed was amazing with two orbs in Najima's cave, two orbs in the Isis castle treasury, and two orbs in the Kidnapper's Cave (one on each screen).

I blew the flute as soon as I entered the Kidnapper's Cave. No echo.

**Comment by gameboy9** [comment]
This is resolved and released, so I will close.  Please reopen if there is still an issue.  Thanks!
