### ISSUE TITLE
Characters not getting names

### ISSUE THREAD

**Issue by Jaylow7** [gameboy9/DW3Randomizer#21]
There is a fairly significant bug with the new option to customize name and class of the pre-generated characters.  The 2nd and 3rd character (the slots that are the Pilgrim and Wizard in vanilla) are generated without a name. 

This can be seen in the attached screenshot.

**Comment by Jaylow7** [comment]
https://imgur.com/9pONAWR

**Comment by gameboy9** [comment]
Resolved in version 2.3.1
